services:
  web:
    build: .
    command: gunicorn djangoTesting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8010:80
    depends_on:
      - web
  database:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

volumes:
  static_volume:
  postgres_data: