# Generated by Django 4.2.16 on 2024-10-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='review',
            field=models.CharField(default='rstsrt', max_length=200),
            preserve_default=False,
        ),
    ]
